services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_BIND=0.0.0.0
      - HUGO_PORT=1313
    # Default to running the development server
    command: hugo server --bind 0.0.0.0 --port 1313 --navigateToChanged
